name: Resource Template Feedback Test
description: Request an improvement to an RT, report a problem with an RT
title: "[RT label or ID] [problem | requested improvement | requested change | etc.]"
labels: RT-FEEDBACK
assignees:
  - briesenberg07

body:
  - type: input
    id: rt_id
    attributes:
      label: Resource Template Label or ID
      description: ""The resource template label is displayed at the top left of the Sinopia data entry form, and will look something like: UWSINOPIA WAU rdaWork monograph CAMS""
    validations:
      required: true
  - type: textarea
    id: problem_description
    attributes:
      label: Problem using the resource template, or request a change
      placeholder: ""Some examples:
      - The property template for [prop IRI or label] is set up for literals, it should be set up for URIs or lookups
      - The lookup source for [prop IRI or label] is wrong, please use this lookup source instead
      - [prop IRI or label] is needed in this template but it isn't here""
      validations:
        required: true
  - type: textarea
    id: relevant_details
    attributes:
      label: Any other relevant details
      placeholder: ""For example, information about the resource you are describing with the template (is it the format for which the template was designed, or a different format, etc.)""
