name: WIKI issue TEST
description: Request addition or improvement to sinopia_maps documentation
title: wiki improvement needed
labels: wiki
assignees:
  - briesenberg07

body:
  - type: textarea
    id: wiki_issue
    attributes:
      label: Describe the issue
      placeholder: "Include one of the following:\n
      - Information about what you are trying to do but can't accomplish due to lack/insufficiency of explanatory documentation\n
      - Specific information you would like made available as a reference in the wiki\n"
    validations:
      required: true
